site_name: CyberSafe Docs
site_description: Documentació bàsica sobre ciberseguretat
site_author: Duna Bou Crespi i Marc Mons Muñoz

theme:
  name: material
  language: ca
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

nav:
  - Inici: index.md

  - Seguretat:
      - Contrasenyes segures: seguretat/contrasenyes.md
      - Autenticació: seguretat/autenticacio.md

  - Xarxes:
      - Firewall: xarxes/firewall.md
      - VPN: xarxes/vpn.md

  - Protecció:
      - Còpies de seguretat: proteccio/copies-seguretat.md
      - Actualitzacions: proteccio/actualitzacions.md

  - Articles:
      - Com protegir un ordinador: articles/protegir-ordinador.md
      - Atacs de phishing: articles/phishing.md
      - Seguretat Wi-Fi: articles/seguretat-wifi.md