
name: Publicar web amb MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descarregar el repositori
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instal·lar MkDocs i el tema
        run: pip install mkdocs-material

      - name: Generar i publicar la web
        run: mkdocs gh-deploy --force